### ISSUE TITLE
Using mysql - fof_config defines FOF_DB_NAME ,  fof-db uses FOF_DB_DBNAME

### ISSUE THREAD

**Issue by pperrin** [fluffy-critter/Feed-on-Feeds#3]
I'll fix and upload etc - but probably not for a while.

**Comment by fluffy-critter** [comment]
A while ago I changed the config params to be `FOF_DB_DBNAME` for MySQL and `FOF_DB_FILENAME` for SQLite so I could make the respective defaults more sensical. I also forgot to change one of the old `FOF_DB_NAME`s in fof-db.php, so you'll need to pull the latest code anyway.

I should probably fix up fof-db to detect missing configuration stuff.

**Comment by fluffy-critter** [comment]
Fixed in 05f78a3
